### ISSUE TITLE
Your ID isn't registered yet...

### ISSUE THREAD

**Issue by aminvakil** [CactusSoft/zabbkit-android#2]
I installed zabbkit-android from https://apkpure.com/zabbkit/ru.zabbkit.android but unfortunately after I login to my zabbix server and go to notifications tab to get my ID it says:

Your ID isn't registered yet...

My co-workers have implemented zabbkit-server and it's working greatly with an iPhone app which they've built before but now I want to have push notifications on zabbkit-android for my own android phone.

What should I do get my ID?

**Comment by yan-oreshchenkov** [comment]
Hi there!
In order to use push notifications, you need at least three components:
1. Mobile app that sends its push notification token to server(2) in exchange for ID
2. Push server glues everything together. The server provides an API that allows to:
2.1 Store push token in exchange for ID
2.2 Send a push message using the ID
3. GCM/APNS channel. The infrastructure has been already developed by Google/Apple that allows to deliver a push message to concrete device. But in order run everything together you have to integrate your app(1) and your server(2) with this part. You need to create an account, receive secrete keys, sign you app with appropriate account's certificate and so on.

So, coming back to your question. CactusSoft has stopped support of Zabbkit, removed the app from markets and *stopped the server part as well*. As I understand the app you installed is a copy from Google Play Market before we deleted it. It tries to connect to disabled server in order to exchange its push token for ID. But it has no chance, service is stopped.

You can try to get up all the infrastructure by yourself, but it will definitely require a certain effort and development skills.

You have mentioned that your colleges have implemented your own push-server? If the API remained the same, you need to change the push-server URL and build your own apk from sources.

**Comment by aminvakil** [comment]
Thanks for your complete instructions. If you could just mention where should I edit push-server URL so I could try building it for myself.

**Comment by yan-oreshchenkov** [comment]
Here it is: https://github.com/CactusSoft/zabbkit-android/blob/7565950a53d18975a5794eab3e2f67948861b405/ZabbkitClient/src/main/java/ru/zabbkit/android/app/Constants.java#L26
